# Generated by Django 4.0.6 on 2022-07-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de director', max_length=100)),
                ('apellido', models.CharField(help_text='nombre de director', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('resumen', models.TextField(help_text='Resumen', max_length=100)),
                ('autor', models.ManyToManyField(to='catalogo.director')),
            ],
        ),
    ]
