# Generated by Django 4.0.4 on 2022-05-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Des', models.TextField()),
                ('Im', models.FilePathField(path='catalogo/static/images')),
            ],
        ),
    ]
