# Generated by Django 4.0.4 on 2022-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ListaR',
            },
        ),
    ]
